steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/cadillac-ev-cis-backend:$COMMIT_SHA', '.']
    
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/cadillac-ev-cis-backend:$COMMIT_SHA']
    
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
    - 'run'
    - 'deploy'
    - 'cadillac-ev-cis-backend'
    - '--image'
    - 'gcr.io/$PROJECT_ID/cadillac-ev-cis-backend:$COMMIT_SHA'
    - '--region'
    - 'europe-west4'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'
    - '--port'
    - '8080'
    - '--memory'
    - '2Gi'
    - '--cpu'
    - '2'
    - '--max-instances'
    - '10'
    - '--min-instances'
    - '0'

images:
- 'gcr.io/$PROJECT_ID/cadillac-ev-cis-backend:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY